spring.application.name=url-shortener

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false


##AppConfig
app.base-url=http://localhost:8080/
app.default-expiry-days=29
app.validate-original-url=true